### ISSUE TITLE
Could you please provide a preferred source for obtaining the checkpoint file?

### ISSUE THREAD

**Issue by Morleynan** [importZL/BLO-SAM#2]
I encountered an issue while trying to reproduce your code: the checkpoint file /data1/li/Auto_SAMed/checkpoints/sam_vit_b_01ec64.pth is missing. Could you please let me know where I can obtain the  file?

**Comment by importZL** [comment]
> I encountered an issue while trying to reproduce your code: the checkpoint file /data1/li/Auto_SAMed/checkpoints/sam_vit_b_01ec64.pth is missing. Could you please let me know where I can obtain the file?

This is a pre-trained checkpoint for the segment anything model from Meta. You can find it in the official SAM repo.
